general:
  kafka-topic: trader-updates
  
server:
        port: 33400

spring:
    kafka:
        producer:
            value-serializer: "org.springframework.kafka.support.serializer.JsonSerializer"
        consumer:
            auto-offset-reset: earliest
            group-id: "midas-core"
            value-deserializer: "org.springframework.kafka.support.serializer.JsonDeserializer"
            properties: 
              spring.json.trusted.packages: "com.jpmc.midascore.foundation"
    